[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
ratatui = "0.26.3"

[[bench]]
name = "generate_solver"
harness = false

[dev-dependencies]
criterion = "0.5.1"
